name: 'walmart_analysis'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

models:
  walmart_analysis:
    staging:
      +schema: SILVER
      +materialized: view

    marts:
      +schema: GOLD
      +materialized: table