SELECT DISTINCT
    STORE AS STORE_ID,
    DATE AS STORE_DATE,
    TEMPERATURE AS STORE_TEMPERATURE,
    FUEL_PRICE,
    COALESCE(MARKDOWN1, 0) AS MARKDOWN1,
    COALESCE(MARKDOWN2, 0) AS MARKDOWN2,
    COALESCE(MARKDOWN3, 0) AS MARKDOWN3,
    COALESCE(MARKDOWN4, 0) AS MARKDOWN4,
    COALESCE(MARKDOWN5, 0) AS MARKDOWN5,
    CPI,
    UNEMPLOYMENT,
    UPPER(TRIM(ISHOLIDAY)) AS IS_HOLIDAY,
    LOAD_TS
FROM {{ source('bronze', 'FACT_RAW') }}
WHERE STORE IS NOT NULL
  AND DATE IS NOT NULL