SELECT DISTINCT
    STORE AS STORE_ID,
    DEPT AS DEPT_ID,
    DATE AS STORE_DATE,
    COALESCE(WEEKLY_SALES, 0) AS STORE_WEEKLY_SALES,
    ISHOLIDAY AS IS_HOLIDAY,
    LOAD_TS
FROM {{ source('bronze', 'DEPARTMENT_RAW') }}
WHERE STORE IS NOT NULL
  AND DEPT IS NOT NULL
  AND DATE IS NOT NULL