SELECT DISTINCT
    STORE_ID,
    STORE_TYPE,
    STORE_SIZE,
    CURRENT_TIMESTAMP() AS INSERT_DATE,
    CURRENT_TIMESTAMP() AS UPDATE_DATE
FROM {{ ref('stg_stores') }}
WHERE STORE_ID IS NOT NULL